apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-scaffolder-ci-cd
  description: Component with GitHub actions enabled.
  annotations:
    github.com/project-slug: 'RoadieHQ/sample-service'
spec:
  type: service
  lifecycle: production
  owner: engineering-team
